FORMAT: 1A
# public

## JSONIP  [/]
### GET [GET]
+ Request (application/json)
    {
    "ip": "116.226.231.82",
    "about": "/about",
    "number": 123.33
    }


+ Response 200 (application/json)
    + Attributes (IPInfo)

## GitHub  [/users/{name}]
### User [GET]
+ Response 200 (application/json)
    + Attributes (UserInfo)

## GitHub  [/repos/vmg/redcarpet/issues]
### Issue [GET]
+ Response 200 (application/json)
    + Attributes (array[Issue])

# Data Structures

## IPInfo (object)
+ ip:  10.100.2.3 (string)
+ about: Hello World (string)
+ users(array[Author])

## Author (object)
+ name: Boba Fett
+ email: fett@intergalactic.com

## UserInfo(object)
+ avatarUrl: (string) 
+ bio: (string) 
+ blog: (string) 
+ company: (string) 
+ createdAt: (string) 
+ email: (string) 
+ eventsUrl: (string) 
+ followers: 22 (number) 
+ followersUrl: (string) 
+ following: 91 (number) 
+ followingUrl: (string) 
+ gistsUrl: (string) 
+ gravatarId: (string) 
+ hireable: (boolean) 
+ htmlUrl: (string) 
+ id: 985343 (number) 
+ location: (string) 
+ login: (string) 
+ name: (string) 
+ organizationsUrl: (string) 
+ publicGists: 0 (number) 
+ publicRepos: 26 (number) 
+ receivedEventsUrl: (string) 
+ reposUrl: (string) 
+ siteAdmin: (boolean) 
+ starredUrl: (string) 
+ subscriptionsUrl: (string) 
+ type: (string) 
+ updatedAt: (string) 
+ url: (string) 

## Issue (object)
+ assignee: (string) 
+ assignees: (array[string]) 
+ body: (string) 
+ closedAt: (string) 
+ comments: 5 (number) 
+ commentsUrl: (string) 
+ createdAt: (string) 
+ eventsUrl: (string) 
+ htmlUrl: (string) 
+ id: 168114317 (number) 
+ labels: (array[string]) 
+ labelsUrl: (string) 
+ locked: (boolean) 
+ milestone: (string) 
+ number: 568 (number) 
+ repositoryUrl: (string) 
+ state: (string) 
+ title: (string) 
+ updatedAt: (string) 
+ url: (string) 
+ user: (IssueUser) 

## IssueUser (object)
+ avatarUrl: (string) 
+ eventsUrl: (string) 
+ followersUrl: (string) 
+ followingUrl: (string) 
+ gistsUrl: (string) 
+ gravatarId: (string) 
+ htmlUrl: (string) 
+ id: 11599514 (number) 
+ login: (string) 
+ organizationsUrl: (string) 
+ receivedEventsUrl: (string) 
+ reposUrl: (string) 
+ siteAdmin: (boolean) 
+ starredUrl: (string) 
+ subscriptionsUrl: (string) 
+ type: (string) 
+ url: (string) 
