FORMAT: 1A
# Fancy

## User  [/api/v1/login]
### Login [POST]
+ Request (application/json)
    {
    "username": "drinking",
    "password": "12345678"
    }


+ Response 200 (application/json)
    + Attributes (LoginResult)

## Meeting [/api/v1/meetinglist.json]
### GetList [GET]
+ Response 200 (application/json)
    + Attributes (MeetingResult)


# Data Structures

## LoginResult (object)
+ error: (string) 
+ login: (string) 
+ token: (string)

## MeetingEntity (object)

## MeetingResult (object)
+ error: (string) 
+ login: (string) 
+ success: (bool)


